-- Reservations rework, step 1 (RESERVATIONS_REWORK.md §7 step 1; docs/features/RESERVATIONS.md §1):
-- generated by drizzle-kit, additive. One hand edit: board_series.retake_deadline becomes an
-- instant, and its old date is kept as the end of that day in Cairo (the board's last day),
-- hence the USING clause drizzle-kit does not write. The old one-active-session index (per type
-- and level) is dropped here; its replacement (per type, year and label) is created by 0043,
-- after the backfill (0042) has labelled every converted window.
CREATE TABLE "board_fee" (
	"id" text PRIMARY KEY NOT NULL,
	"board_series_id" text NOT NULL,
	"key_kind" text NOT NULL,
	"unit_id" text,
	"qualification_option_id" text,
	"qualification_id" text,
	"subject_id" text,
	"key_id" text GENERATED ALWAYS AS (COALESCE("unit_id", "qualification_option_id", "qualification_id", "subject_id")) STORED NOT NULL,
	"amount" numeric(12, 2) NOT NULL,
	"provisional" boolean DEFAULT true NOT NULL,
	"confirmed_at" timestamp with time zone,
	"confirmed_by" text,
	"zero_reason" text,
	"copied_from_fee_id" text,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "board_fee_key_one" CHECK (
      ("board_fee"."key_kind" = 'unit' AND "board_fee"."unit_id" IS NOT NULL AND num_nonnulls("board_fee"."qualification_option_id", "board_fee"."qualification_id", "board_fee"."subject_id") = 0)
      OR ("board_fee"."key_kind" = 'option' AND "board_fee"."qualification_option_id" IS NOT NULL AND num_nonnulls("board_fee"."unit_id", "board_fee"."qualification_id", "board_fee"."subject_id") = 0)
      OR ("board_fee"."key_kind" = 'qualification' AND "board_fee"."qualification_id" IS NOT NULL AND num_nonnulls("board_fee"."unit_id", "board_fee"."qualification_option_id", "board_fee"."subject_id") = 0)
      OR ("board_fee"."key_kind" = 'subject' AND "board_fee"."subject_id" IS NOT NULL AND num_nonnulls("board_fee"."unit_id", "board_fee"."qualification_option_id", "board_fee"."qualification_id") = 0)),
	CONSTRAINT "board_fee_amount_nonneg" CHECK ("board_fee"."amount" >= 0),
	CONSTRAINT "board_fee_zero_has_reason" CHECK ("board_fee"."amount" > 0 OR "board_fee"."zero_reason" IS NOT NULL),
	CONSTRAINT "board_fee_confirmed_whole" CHECK (("board_fee"."provisional" AND "board_fee"."confirmed_at" IS NULL) OR (NOT "board_fee"."provisional" AND "board_fee"."confirmed_at" IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "registration_consent" (
	"id" text PRIMARY KEY NOT NULL,
	"registration_id" text NOT NULL,
	"kind" text NOT NULL,
	"text_version" text NOT NULL,
	"confirmed_by" text,
	"channel" text NOT NULL,
	"at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "registration_consent_kind_valid" CHECK ("registration_consent"."kind" IN ('refund_policy', 'declaration')),
	CONSTRAINT "registration_consent_channel_valid" CHECK ("registration_consent"."channel" IN ('app', 'desk', 'school', 'imported'))
);
--> statement-breakpoint
CREATE TABLE "session_offer" (
	"id" text PRIMARY KEY NOT NULL,
	"session_id" text NOT NULL,
	"subject_id" text NOT NULL,
	"availability" text DEFAULT 'open' NOT NULL,
	"course_fee" numeric(12, 2) DEFAULT 0 NOT NULL,
	"course_starts_on" date,
	"grade10_core" boolean DEFAULT false NOT NULL,
	"notes" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"legacy" jsonb,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "sessionOffer_session_subject_key" UNIQUE("session_id","subject_id"),
	CONSTRAINT "sessionOffer_id_session_key" UNIQUE("id","session_id"),
	CONSTRAINT "session_offer_availability_valid" CHECK ("session_offer"."availability" IN ('open', 'retake_only', 'self_study_only', 'closed')),
	CONSTRAINT "session_offer_course_fee_nonneg" CHECK ("session_offer"."course_fee" >= 0)
);
--> statement-breakpoint
CREATE TABLE "session_offer_item" (
	"id" text PRIMARY KEY NOT NULL,
	"offer_id" text NOT NULL,
	"session_id" text NOT NULL,
	"label" text NOT NULL,
	"kind" text DEFAULT 'whole' NOT NULL,
	"enters_kind" text NOT NULL,
	"qualification_id" text,
	"qualification_option_id" text,
	"board_series_id" text,
	"availability" text DEFAULT 'open' NOT NULL,
	"course_fee" numeric(12, 2),
	"needs_prior_series" boolean DEFAULT false NOT NULL,
	"required_in_series" boolean DEFAULT false NOT NULL,
	"exclusive_group" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"legacy" jsonb,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "session_offer_item_kind_valid" CHECK ("session_offer_item"."kind" IN ('whole', 'one_paper', 'unit', 'route', 'qualification')),
	CONSTRAINT "session_offer_item_enters_valid" CHECK (("session_offer_item"."enters_kind" = 'award' AND "session_offer_item"."qualification_id" IS NOT NULL) OR ("session_offer_item"."enters_kind" = 'option' AND "session_offer_item"."qualification_option_id" IS NOT NULL) OR "session_offer_item"."enters_kind" IN ('units', 'subject')),
	CONSTRAINT "session_offer_item_availability_valid" CHECK ("session_offer_item"."availability" IN ('open', 'retake_only', 'self_study_only', 'closed')),
	CONSTRAINT "session_offer_item_course_fee_nonneg" CHECK ("session_offer_item"."course_fee" IS NULL OR "session_offer_item"."course_fee" >= 0)
);
--> statement-breakpoint
CREATE TABLE "session_offer_item_fee_key" (
	"id" text PRIMARY KEY NOT NULL,
	"item_id" text NOT NULL,
	"key_kind" text NOT NULL,
	"unit_id" text,
	"qualification_option_id" text,
	"qualification_id" text,
	"subject_id" text,
	"key_id" text GENERATED ALWAYS AS (COALESCE("unit_id", "qualification_option_id", "qualification_id", "subject_id")) STORED NOT NULL,
	CONSTRAINT "session_offer_item_fee_key_one" CHECK (
      ("session_offer_item_fee_key"."key_kind" = 'unit' AND "session_offer_item_fee_key"."unit_id" IS NOT NULL AND num_nonnulls("session_offer_item_fee_key"."qualification_option_id", "session_offer_item_fee_key"."qualification_id", "session_offer_item_fee_key"."subject_id") = 0)
      OR ("session_offer_item_fee_key"."key_kind" = 'option' AND "session_offer_item_fee_key"."qualification_option_id" IS NOT NULL AND num_nonnulls("session_offer_item_fee_key"."unit_id", "session_offer_item_fee_key"."qualification_id", "session_offer_item_fee_key"."subject_id") = 0)
      OR ("session_offer_item_fee_key"."key_kind" = 'qualification' AND "session_offer_item_fee_key"."qualification_id" IS NOT NULL AND num_nonnulls("session_offer_item_fee_key"."unit_id", "session_offer_item_fee_key"."qualification_option_id", "session_offer_item_fee_key"."subject_id") = 0)
      OR ("session_offer_item_fee_key"."key_kind" = 'subject' AND "session_offer_item_fee_key"."subject_id" IS NOT NULL AND num_nonnulls("session_offer_item_fee_key"."unit_id", "session_offer_item_fee_key"."qualification_option_id", "session_offer_item_fee_key"."qualification_id") = 0))
);
--> statement-breakpoint
CREATE TABLE "session_offer_item_teacher" (
	"id" text PRIMARY KEY NOT NULL,
	"item_id" text NOT NULL,
	"teacher_id" text NOT NULL,
	"mode" text DEFAULT 'in_school' NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "session_offer_item_teacher_mode_valid" CHECK ("session_offer_item_teacher"."mode" IN ('in_school', 'online'))
);
--> statement-breakpoint
CREATE TABLE "session_offer_item_unit" (
	"item_id" text NOT NULL,
	"unit_id" text NOT NULL,
	CONSTRAINT "session_offer_item_unit_item_id_unit_id_pk" PRIMARY KEY("item_id","unit_id")
);
--> statement-breakpoint
CREATE TABLE "session_offer_teacher" (
	"id" text PRIMARY KEY NOT NULL,
	"offer_id" text NOT NULL,
	"teacher_id" text NOT NULL,
	"mode" text DEFAULT 'in_school' NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "session_offer_teacher_mode_valid" CHECK ("session_offer_teacher"."mode" IN ('in_school', 'online'))
);
--> statement-breakpoint
DROP INDEX "one_active_per_session_type_idx";--> statement-breakpoint
DROP INDEX "courseEnrolment_one_open_idx";--> statement-breakpoint
ALTER TABLE "board_series" ALTER COLUMN "retake_deadline" SET DATA TYPE timestamp with time zone USING (("retake_deadline" + time '23:59:59') AT TIME ZONE 'Africa/Cairo');--> statement-breakpoint
ALTER TABLE "registration_session" ALTER COLUMN "qualification_level" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "registration_session" ALTER COLUMN "qualification_level" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "change_request" ADD COLUMN "new_offer_item_id" text;--> statement-breakpoint
ALTER TABLE "course_enrolment" ADD COLUMN "unit_id" text;--> statement-breakpoint
ALTER TABLE "exam_board" ADD COLUMN "carry_forward_months" integer;--> statement-breakpoint
ALTER TABLE "registration" ADD COLUMN "offer_item_id" text;--> statement-breakpoint
ALTER TABLE "registration" ADD COLUMN "attempt" text DEFAULT 'first' NOT NULL;--> statement-breakpoint
ALTER TABLE "registration" ADD COLUMN "mode" text DEFAULT 'in_school' NOT NULL;--> statement-breakpoint
ALTER TABLE "registration" ADD COLUMN "prior_sitting_series_id" text;--> statement-breakpoint
ALTER TABLE "registration" ADD COLUMN "prior_sitting_source" text;--> statement-breakpoint
ALTER TABLE "registration" ADD COLUMN "prior_centre" text;--> statement-breakpoint
ALTER TABLE "registration" ADD COLUMN "prior_candidate_number" text;--> statement-breakpoint
ALTER TABLE "registration" ADD COLUMN "due_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "registration" ADD COLUMN "price_provisional" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "registration" ADD COLUMN "pricing_basis" jsonb;--> statement-breakpoint
ALTER TABLE "registration" ADD COLUMN "refund_policy_snapshot" jsonb;--> statement-breakpoint
ALTER TABLE "registration" ADD COLUMN "legacy" jsonb;--> statement-breakpoint
ALTER TABLE "registration_session" ADD COLUMN "label" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "registration_session" ADD COLUMN "course_starts_on" date;--> statement-breakpoint
ALTER TABLE "registration_session" ADD COLUMN "refund_policy" jsonb;--> statement-breakpoint
ALTER TABLE "registration_session" ADD COLUMN "payment_due_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "teacher" ADD COLUMN "kind" text DEFAULT 'person' NOT NULL;--> statement-breakpoint
ALTER TABLE "board_fee" ADD CONSTRAINT "board_fee_board_series_id_board_series_id_fk" FOREIGN KEY ("board_series_id") REFERENCES "public"."board_series"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "board_fee" ADD CONSTRAINT "board_fee_unit_id_exam_unit_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."exam_unit"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "board_fee" ADD CONSTRAINT "board_fee_qualification_option_id_qualification_option_id_fk" FOREIGN KEY ("qualification_option_id") REFERENCES "public"."qualification_option"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "board_fee" ADD CONSTRAINT "board_fee_qualification_id_qualification_id_fk" FOREIGN KEY ("qualification_id") REFERENCES "public"."qualification"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "board_fee" ADD CONSTRAINT "board_fee_subject_id_subject_id_fk" FOREIGN KEY ("subject_id") REFERENCES "public"."subject"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "board_fee" ADD CONSTRAINT "board_fee_confirmed_by_user_id_fk" FOREIGN KEY ("confirmed_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "board_fee" ADD CONSTRAINT "board_fee_copied_from_fee_id_board_fee_id_fk" FOREIGN KEY ("copied_from_fee_id") REFERENCES "public"."board_fee"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "board_fee" ADD CONSTRAINT "board_fee_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "registration_consent" ADD CONSTRAINT "registration_consent_registration_id_registration_id_fk" FOREIGN KEY ("registration_id") REFERENCES "public"."registration"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "registration_consent" ADD CONSTRAINT "registration_consent_confirmed_by_user_id_fk" FOREIGN KEY ("confirmed_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_offer" ADD CONSTRAINT "session_offer_session_id_registration_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."registration_session"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_offer" ADD CONSTRAINT "session_offer_subject_id_subject_id_fk" FOREIGN KEY ("subject_id") REFERENCES "public"."subject"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_offer" ADD CONSTRAINT "session_offer_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_offer_item" ADD CONSTRAINT "session_offer_item_qualification_id_qualification_id_fk" FOREIGN KEY ("qualification_id") REFERENCES "public"."qualification"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_offer_item" ADD CONSTRAINT "session_offer_item_qualification_option_id_qualification_option_id_fk" FOREIGN KEY ("qualification_option_id") REFERENCES "public"."qualification_option"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_offer_item" ADD CONSTRAINT "session_offer_item_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_offer_item" ADD CONSTRAINT "sessionOfferItem_offer_fk" FOREIGN KEY ("offer_id","session_id") REFERENCES "public"."session_offer"("id","session_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_offer_item" ADD CONSTRAINT "sessionOfferItem_series_link_fk" FOREIGN KEY ("session_id","board_series_id") REFERENCES "public"."session_board_series"("session_id","board_series_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_offer_item_fee_key" ADD CONSTRAINT "session_offer_item_fee_key_item_id_session_offer_item_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."session_offer_item"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_offer_item_fee_key" ADD CONSTRAINT "session_offer_item_fee_key_unit_id_exam_unit_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."exam_unit"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_offer_item_fee_key" ADD CONSTRAINT "session_offer_item_fee_key_qualification_option_id_qualification_option_id_fk" FOREIGN KEY ("qualification_option_id") REFERENCES "public"."qualification_option"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_offer_item_fee_key" ADD CONSTRAINT "session_offer_item_fee_key_qualification_id_qualification_id_fk" FOREIGN KEY ("qualification_id") REFERENCES "public"."qualification"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_offer_item_fee_key" ADD CONSTRAINT "session_offer_item_fee_key_subject_id_subject_id_fk" FOREIGN KEY ("subject_id") REFERENCES "public"."subject"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_offer_item_teacher" ADD CONSTRAINT "session_offer_item_teacher_item_id_session_offer_item_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."session_offer_item"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_offer_item_teacher" ADD CONSTRAINT "session_offer_item_teacher_teacher_id_teacher_id_fk" FOREIGN KEY ("teacher_id") REFERENCES "public"."teacher"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_offer_item_unit" ADD CONSTRAINT "session_offer_item_unit_item_id_session_offer_item_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."session_offer_item"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_offer_item_unit" ADD CONSTRAINT "session_offer_item_unit_unit_id_exam_unit_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."exam_unit"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_offer_teacher" ADD CONSTRAINT "session_offer_teacher_offer_id_session_offer_id_fk" FOREIGN KEY ("offer_id") REFERENCES "public"."session_offer"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_offer_teacher" ADD CONSTRAINT "session_offer_teacher_teacher_id_teacher_id_fk" FOREIGN KEY ("teacher_id") REFERENCES "public"."teacher"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "boardFee_series_key_idx" ON "board_fee" USING btree ("board_series_id","key_kind","key_id");--> statement-breakpoint
CREATE INDEX "boardFee_key_idx" ON "board_fee" USING btree ("key_kind","key_id");--> statement-breakpoint
CREATE UNIQUE INDEX "registrationConsent_unique_idx" ON "registration_consent" USING btree ("registration_id","kind");--> statement-breakpoint
CREATE INDEX "sessionOffer_subjectId_idx" ON "session_offer" USING btree ("subject_id");--> statement-breakpoint
CREATE INDEX "sessionOfferItem_offerId_idx" ON "session_offer_item" USING btree ("offer_id");--> statement-breakpoint
CREATE INDEX "sessionOfferItem_sessionId_idx" ON "session_offer_item" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "sessionOfferItem_boardSeriesId_idx" ON "session_offer_item" USING btree ("board_series_id");--> statement-breakpoint
CREATE UNIQUE INDEX "sessionOfferItemFeeKey_unique_idx" ON "session_offer_item_fee_key" USING btree ("item_id","key_kind","key_id");--> statement-breakpoint
CREATE INDEX "sessionOfferItemFeeKey_key_idx" ON "session_offer_item_fee_key" USING btree ("key_kind","key_id");--> statement-breakpoint
CREATE UNIQUE INDEX "sessionOfferItemTeacher_unique_idx" ON "session_offer_item_teacher" USING btree ("item_id","teacher_id");--> statement-breakpoint
CREATE INDEX "sessionOfferItemTeacher_teacherId_idx" ON "session_offer_item_teacher" USING btree ("teacher_id");--> statement-breakpoint
CREATE INDEX "sessionOfferItemUnit_unitId_idx" ON "session_offer_item_unit" USING btree ("unit_id");--> statement-breakpoint
CREATE UNIQUE INDEX "sessionOfferTeacher_unique_idx" ON "session_offer_teacher" USING btree ("offer_id","teacher_id");--> statement-breakpoint
CREATE INDEX "sessionOfferTeacher_teacherId_idx" ON "session_offer_teacher" USING btree ("teacher_id");--> statement-breakpoint
ALTER TABLE "change_request" ADD CONSTRAINT "change_request_new_offer_item_id_session_offer_item_id_fk" FOREIGN KEY ("new_offer_item_id") REFERENCES "public"."session_offer_item"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "course_enrolment" ADD CONSTRAINT "course_enrolment_unit_id_exam_unit_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."exam_unit"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "registration" ADD CONSTRAINT "registration_offer_item_id_session_offer_item_id_fk" FOREIGN KEY ("offer_item_id") REFERENCES "public"."session_offer_item"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "registration" ADD CONSTRAINT "registration_prior_sitting_series_id_board_series_id_fk" FOREIGN KEY ("prior_sitting_series_id") REFERENCES "public"."board_series"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "courseEnrolment_one_open_unit_idx" ON "course_enrolment" USING btree ("student_id","unit_id","academic_year_id") WHERE ended_on IS NULL AND unit_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX "courseEnrolment_unitId_idx" ON "course_enrolment" USING btree ("unit_id");--> statement-breakpoint
CREATE INDEX "registration_offerItemId_idx" ON "registration" USING btree ("offer_item_id");--> statement-breakpoint
CREATE INDEX "registration_priorSittingSeriesId_idx" ON "registration" USING btree ("prior_sitting_series_id");--> statement-breakpoint
CREATE UNIQUE INDEX "courseEnrolment_one_open_idx" ON "course_enrolment" USING btree ("student_id","subject_id","academic_year_id") WHERE ended_on IS NULL AND unit_id IS NULL;--> statement-breakpoint
ALTER TABLE "exam_board" ADD CONSTRAINT "exam_board_carry_forward_months_range" CHECK ("exam_board"."carry_forward_months" IS NULL OR "exam_board"."carry_forward_months" BETWEEN 1 AND 60);--> statement-breakpoint
ALTER TABLE "registration" ADD CONSTRAINT "registration_attempt_valid" CHECK ("registration"."attempt" IN ('first', 'retake'));--> statement-breakpoint
ALTER TABLE "registration" ADD CONSTRAINT "registration_mode_valid" CHECK ("registration"."mode" IN ('in_school', 'self_study'));--> statement-breakpoint
ALTER TABLE "registration" ADD CONSTRAINT "registration_prior_sitting_source_valid" CHECK ("registration"."prior_sitting_source" IS NULL OR "registration"."prior_sitting_source" IN ('known', 'declared_by_desk', 'declared_by_family', 'legacy'));--> statement-breakpoint
ALTER TABLE "teacher" ADD CONSTRAINT "teacher_kind_valid" CHECK ("teacher"."kind" IN ('person', 'provider'));--> statement-breakpoint
ALTER TABLE "teacher" ADD CONSTRAINT "teacher_provider_no_account" CHECK ("teacher"."kind" <> 'provider' OR "teacher"."user_id" IS NULL);