/**
 * Audit Log Validation Schemas
 *
 * Zod schemas for the audit trail system (REP-006).
 *
 * AUDIT_ACTIONS covers every significant system operation:
 * - Subject CRUD
 * - Session lifecycle
 * - Registration approval flow
 * - Payment lifecycle
 * - Change request (drop/swap) flow
 * - Escrow operations
 * - User / grade management
 * - Admin broadcasts
 *
 * AUDIT_ENTITY_TYPES matches the entityType column — links each log entry
 * back to the domain entity it describes.
 *
 * AuditLogsQuery drives the admin audit log viewer (REP-006):
 * filterable by userId, action, entityType, dateFrom, dateTo, and
 * paginated via limit/offset.
 */

import { z } from 'zod';

// ─── Entity Types ─────────────────────────────────────────────────────────────

export const AUDIT_ENTITY_TYPES = [
  'user',
  'subject',
  'session',
  'registration',
  'payment',
  'escrow',
  'change_request',
  'notification',
  'teacher',
  'school_fee_schedule',
  'receipt',
  'refund_window',
  'exception',
  'remark_request',
  'link',
  'remark_fee',
  'remark_deadline',
  // F0a
  'setting',
  'academic_year',
  'term',
  'calendar_entry',
  'bell_schedule',
  'room',
  'section',
  'file',
  // F0b
  'board',
  'qualification',
  'exam_unit',
  'qualification_option',
  'board_series',
  'enrolment',
  // Reservations rework
  'session_offer',
  'offer_item',
  'board_fee',
  // Reservations rework, step C: charges and board services
  'charge',
  'board_service',
  // F1
  'teaching_group',
  'timetable',
  'schedule_rules',
  'teacher_absence',
  'cover_assignment',
  'calendar_feed',
] as const;

export const AuditEntityTypeSchema = z.enum(AUDIT_ENTITY_TYPES);
export type AuditEntityType = z.infer<typeof AuditEntityTypeSchema>;

export const AUDIT_ENTITY_TYPE_LABELS: Record<AuditEntityType, string> = {
  user:           'User',
  subject:        'Subject',
  session:        'Session',
  registration:   'Registration',
  payment:        'Payment',
  escrow:         'Escrow',
  change_request: 'Change Request',
  notification:   'Notification',
  teacher:        'Teacher',
  school_fee_schedule: 'School Fee Schedule',
  receipt:        'Receipt',
  refund_window:  'Refund Window',
  exception:      'Exception',
  remark_request: 'Remark Request',
  link:           'Parent-Student Link',
  remark_fee:     'Remark Fee',
  remark_deadline:'Remark Deadline',
  setting:        'Setting',
  academic_year:  'Academic Year',
  term:           'Term',
  calendar_entry: 'Calendar Day',
  bell_schedule:  'Bell Schedule',
  room:           'Room',
  section:        'Section',
  file:           'File',
  board:          'Exam Board',
  qualification:  'Qualification',
  exam_unit:      'Unit or Component',
  qualification_option: 'Option Code',
  board_series:   'Board Series',
  enrolment:      'Course Enrolment',
  session_offer:  'Session Subject (Offer)',
  offer_item:     'Offer Item',
  board_fee:      'Board Fee',
  charge:         'Charge',
  board_service:  'Board Service',
  teaching_group: 'Teaching Group',
  timetable:      'Timetable',
  schedule_rules: 'Timetable Rules',
  teacher_absence: 'Teacher Absence',
  cover_assignment: 'Cover',
  calendar_feed:  'Calendar Feed',
};

// ─── Action Types ─────────────────────────────────────────────────────────────

export const AUDIT_ACTIONS = [
  // Subject management
  'SUBJECT_CREATED',
  'SUBJECT_UPDATED',
  'SUBJECT_DEACTIVATED',
  'SUBJECT_ACTIVATED',
  'SUBJECT_CORE_UPDATED',
  // Session lifecycle
  'SESSION_CREATED',
  'SESSION_UPDATED',
  'SESSION_ENTRY_DEADLINE_SET',
  'SESSION_ACTIVATED',
  'SESSION_CLOSED',
  'SESSION_AUTO_CLOSED',
  'SESSION_AUTO_ACTIVATED',
  // Registration flow
  'REGISTRATION_REQUESTED',
  'REGISTRATION_DIRECT',
  'REGISTRATION_APPROVED',
  'REGISTRATION_APPROVAL_REVERTED',
  'REGISTRATION_REJECTED',
  'REGISTRATION_ADMIN_OVERRIDE',
  'REGISTRATION_CONFIRMED',
  // A registration the system expired: at a close, at an entry deadline, at
  // graduation, or with a failed checkout once its window had closed (SO-1).
  'REGISTRATION_EXPIRED',
  // Payment lifecycle
  'PAYMENT_INITIATED',
  'PAYMENT_CONFIRMED',
  'PAYMENT_FAILED',
  'PAYMENT_CANCELLED',
  'PAYMENT_REJECTED',
  'PAYMENT_LATE_TRANSFER_RECORDED',
  'PAYMENT_LATE_TRANSFER_UNDONE',
  'PAYMENT_REFERENCE_SUBMITTED',
  'TEACHER_CREATED',
  'TEACHER_UPDATED',
  'TEACHER_DEACTIVATED',
  'SCHOOL_FEE_SCHEDULE_CREATED',
  'SCHOOL_FEE_SCHEDULE_UPDATED',
  'SCHOOL_FEE_SCHEDULE_DELETED',
  'SCHOOL_FEE_PAYMENT_INITIATED',
  'RECEIPT_ISSUED',
  'RECEIPT_RETURNED',
  'RECEIPT_LOST',
  'RECEIPT_VOIDED',
  'REFUND_WINDOW_CREATED',
  'REFUND_WINDOW_DELETED',
  'WITHDRAWAL_APPROVED',
  'EXCEPTION_GRANTED',
  'EXCEPTION_REVOKED',
  'EXCEPTION_LAPSED',
  'PREREG_CREATED',
  'PREREG_CANCELLED',
  'PREREG_CAPTURED',
  'PREREG_HELD_INELIGIBLE',
  'PREREG_REFUNDED_AT_DEADLINE',
  'REMARK_REQUESTED',
  'REMARK_APPROVED',
  'REMARK_REJECTED',
  'REMARK_CONSENT_CONFIRMED',
  'REMARK_SUBMITTED_TO_BOARD',
  'REMARK_OUTCOME_RECORDED',
  'REMARK_CANCELLED',
  'RESULTS_RECORDED',
  'STAFF_USER_CREATED',
  'DESK_FAMILY_ONBOARDED',
  'DESK_REGISTRATION',
  'DESK_SCHOOL_FEE_COLLECTED',
  'PAYMENT_REVERSED',
  // Change requests
  'CHANGE_REQUEST_CREATED',
  'CHANGE_REQUEST_APPROVED',
  'CHANGE_REQUEST_REJECTED',
  'CHANGE_REQUEST_CANCELLED',
  'DIRECT_DROP_EXECUTED',
  'DIRECT_SWAP_EXECUTED',
  // Escrow
  'ESCROW_TRANSFER',
  'WITHDRAWAL_REQUESTED',
  'WITHDRAWAL_FULFILLED',
  'WITHDRAWAL_REJECTED',
  // User / grade
  'USER_UPDATED',
  'USER_UPDATED_BY_ADMIN',
  // Kept for history: grades moved by window closes and by hand until F0a
  // replaced the stored grade with the cohort.
  'USER_GRADE_CHANGED',
  // F0a: the student record
  'STUDENT_COHORT_CORRECTED',
  'STUDENT_COHORT_INFERRED',
  'STUDENT_COHORT_RECORDED',
  'STUDENT_COHORT_UNRECORDED',
  'STUDENT_LEFT',
  'STUDENT_READMITTED',
  'TEACHER_ACCOUNT_LINKED',
  'SESSION_SERIES_CORRECTED',
  // F0a: settings and uploads
  'SETTING_CHANGED',
  'FILE_UPLOADED',
  // F0a: academic structure
  'ACADEMIC_YEAR_CREATED',
  'ACADEMIC_YEAR_UPDATED',
  'TERM_CREATED',
  'TERM_UPDATED',
  'TERM_DELETED',
  'CALENDAR_ENTRY_CREATED',
  'CALENDAR_ENTRY_DELETED',
  'BELL_SCHEDULE_CREATED',
  'BELL_SCHEDULE_UPDATED',
  'BELL_PERIODS_REPLACED',
  'BELL_SCHEDULE_DELETED',
  'ROOM_CREATED',
  'ROOM_UPDATED',
  'SECTION_CREATED',
  'SECTION_UPDATED',
  'SECTION_DELETED',
  'SECTION_MEMBERS_ADDED',
  'SECTION_MEMBERSHIP_ENDED',
  'SECTIONS_ROLLED_OVER',
  // F0b: the exam catalogue, board series and course enrolment
  'BOARD_UPDATED',
  'QUALIFICATION_CREATED',
  'QUALIFICATION_UPDATED',
  'QUALIFICATION_UNITS_SET',
  'QUALIFICATION_OPTION_CREATED',
  'QUALIFICATION_OPTION_UPDATED',
  'EXAM_UNIT_CREATED',
  'EXAM_UNIT_UPDATED',
  'SUBJECT_CATALOGUE_MAPPED',
  'CATALOGUE_STARTER_LOADED',
  'BOARD_SERIES_CREATED',
  'BOARD_SERIES_UPDATED',
  'BOARD_SERIES_DELETED',
  'BOARD_SERIES_DEADLINE_SET',
  'SESSION_BOARD_SERIES_SET',
  'REGISTRATION_SERIES_MOVED',
  'SUBJECT_ROUTE_MOVED',
  'SUBJECT_BOARD_CHANGED',
  'SUBJECT_BOARD_INFERRED',
  'REGISTRATION_SERIES_INFERRED',
  'REGISTRATION_SERIES_INFERENCE_CHECKED',
  'SUBJECT_NOT_OFFERED_INFERRED',
  'SUBJECT_BOARD_INFERENCE_CHECKED',
  'ENROLMENT_CREATED',
  'ENROLMENT_UPDATED',
  'ENROLMENT_ENDED',
  'ENROLMENTS_BULK_CREATED',
  // Reservations rework (step 1)
  'REWORK_BACKFILL_SESSION',
  'REWORK_BACKFILL_OFFER',
  'REWORK_BACKFILL_FEE',
  'REWORK_BACKFILL_LINE',
  'SESSION_COPIED',
  'SESSION_OFFER_CREATED',
  'SESSION_OFFER_UPDATED',
  'SESSION_OFFER_DELETED',
  'SESSION_OFFER_TEACHER_REPLACED',
  'OFFER_ITEM_CREATED',
  'OFFER_ITEM_UPDATED',
  'OFFER_ITEM_DELETED',
  'OFFER_ITEM_SERIES_CHANGED',
  'LINE_SERIES_MOVED',
  'LINE_TEACHER_REPLACED',
  'BOARD_FEES_SET',
  'BOARD_FEES_COPIED',
  'BOARD_FEES_CONFIRMED',
  'BOARD_FEES_REPRICED',
  'LINE_REPRICED',
  // A re-price left a line's price as it was (it has a payment) and cleared its provisional mark.
  'LINE_PRICE_KEPT',
  'LINE_DUE_MOVED',
  'GRADE10_BULK_COMMITTED',
  // Reservations rework, step C: charges, plans, the registry, board services, the desk-drop
  'CHARGE_CREATED',
  'CHARGE_REQUESTED',
  'CHARGE_ACCEPTED',
  'CHARGE_CANCELLED',
  'CHARGE_REPRICED',
  'CHARGE_PAID',
  'CHARGE_REOPENED',
  'CHARGE_SETTLED',
  'CHARGE_REFUNDED',
  'CHARGE_CLOSED_AT_DEADLINE',
  'CHARGE_PAYMENT_INITIATED',
  'SCHOOL_FEE_PUSHED',
  'PLAN_CAPTURED',
  'PLAN_SETTLED',
  'EXCEPTION_CONFIRMED',
  'EXCEPTION_USED',
  'BOARD_SERVICE_UPDATED',
  'SERVICE_DEADLINES_SET',
  'SERVICE_FEES_SET',
  'SERVICE_FEE_DEFAULT_COPIED',
  'DESK_DROP_EXECUTED',
  'REWORK_BACKFILL_EXCEPTION',
  'REWORK_BACKFILL_SERVICE',
  // Reservations rework, step B (declared sittings, the teacher on a line)
  'PRIOR_SITTING_VERIFIED',
  'PRIOR_SITTING_REJECTED',
  'LINE_DROPPED_UNVERIFIED',
  'LINE_TEACHER_CHANGED',
  // F1: scheduling
  'TEACHING_GROUPS_FORMED',
  'TEACHING_GROUP_CREATED',
  'TEACHING_GROUP_UPDATED',
  'TEACHING_GROUP_MEMBERS_ADDED',
  'TEACHING_GROUP_MEMBERS_ENDED',
  'TEACHING_GROUP_SPLIT',
  'TEACHING_GROUPS_MERGED',
  'TEACHING_GROUP_ARCHIVED',
  'SCHEDULE_RULES_SET',
  'TIMETABLE_CREATED',
  'TIMETABLE_UPDATED',
  'TIMETABLE_DELETED',
  'TIMETABLE_LESSON_MOVED',
  'TIMETABLE_LESSON_LOCKED',
  'TIMETABLE_GENERATED',
  'TIMETABLE_PUBLISHED',
  'TEACHER_ABSENCE_RECORDED',
  'TEACHER_ABSENCE_CANCELLED',
  'COVER_ASSIGNED',
  'LESSON_CANCELLED',
  'COVER_REMOVED',
  'CALENDAR_FEED_CREATED',
  'CALENDAR_FEED_REVOKED',
  // Parent-student links (security audit RF-14: access to a child's money
  // and records hangs on these, so every change is recorded)
  'LINK_REQUESTED',
  'LINK_APPROVED',
  'LINK_REJECTED',
  'LINK_REMOVED',
  // Remark configuration and payment
  'REMARK_FEE_SET',
  'REMARK_DEADLINE_SET',
  'REMARK_PAYMENT_INITIATED',
  'REMARK_PAYMENT_CONFIRMED',
  // Admin
  'ADMIN_ANNOUNCEMENT',
] as const;

export const AuditActionSchema = z.enum(AUDIT_ACTIONS);
export type AuditAction = z.infer<typeof AuditActionSchema>;

export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  SUBJECT_CREATED:            'Subject Created',
  SUBJECT_UPDATED:            'Subject Updated',
  SUBJECT_DEACTIVATED:        'Subject Deactivated',
  SUBJECT_ACTIVATED:          'Subject Reactivated',
  SUBJECT_CORE_UPDATED:       'Core Subject Flag Updated',
  SESSION_CREATED:            'Session Created',
  SESSION_UPDATED:            'Session Updated',
  SESSION_ENTRY_DEADLINE_SET: 'Board Entry Deadline Set',
  SESSION_ACTIVATED:          'Session Activated',
  SESSION_CLOSED:             'Session Closed',
  SESSION_AUTO_CLOSED:        'Session Auto-Closed',
  SESSION_AUTO_ACTIVATED:     'Session Auto-Activated',
  REGISTRATION_REQUESTED:     'Registration Request Submitted',
  REGISTRATION_DIRECT:        'Direct Registration by Parent',
  REGISTRATION_APPROVED:      'Registration Request Approved',
  REGISTRATION_APPROVAL_REVERTED: 'Registration Approval Reverted',
  REGISTRATION_REJECTED:      'Registration Request Rejected',
  REGISTRATION_ADMIN_OVERRIDE:'Admin Override Applied',
  REGISTRATION_CONFIRMED:     'Registration Confirmed (Payment)',
  REGISTRATION_EXPIRED:       'Registration Expired (System)',
  PAYMENT_INITIATED:          'Payment Initiated',
  PAYMENT_CONFIRMED:          'Payment Confirmed',
  PAYMENT_FAILED:             'Payment Failed',
  PAYMENT_CANCELLED:          'Payment Cancelled by Parent',
  PAYMENT_REJECTED:           'Payment Rejected by Finance',
  PAYMENT_LATE_TRANSFER_RECORDED: 'Transfer Found Later — Credited to Escrow',
  PAYMENT_LATE_TRANSFER_UNDONE: 'Transfer Found Later — Undone',
  PAYMENT_REFERENCE_SUBMITTED:'InstaPay Reference Submitted',
  TEACHER_CREATED:            'Teacher Created',
  TEACHER_UPDATED:            'Teacher Updated',
  TEACHER_DEACTIVATED:        'Teacher Deactivated',
  SCHOOL_FEE_SCHEDULE_CREATED:'School Fee Schedule Created',
  SCHOOL_FEE_SCHEDULE_UPDATED:'School Fee Schedule Updated',
  SCHOOL_FEE_SCHEDULE_DELETED:'School Fee Schedule Deleted',
  SCHOOL_FEE_PAYMENT_INITIATED:'School Fee Payment Initiated',
  RECEIPT_ISSUED:             'Receipt Handed to Parent',
  RECEIPT_RETURNED:           'Receipt Returned to School',
  RECEIPT_LOST:               'Receipt Marked Lost',
  RECEIPT_VOIDED:             'Receipt Voided',
  REFUND_WINDOW_CREATED:      'Refund Window Created',
  REFUND_WINDOW_DELETED:      'Refund Window Deleted',
  WITHDRAWAL_APPROVED:        'Withdrawal Approved (Finance Admin)',
  EXCEPTION_GRANTED:          'Exception Granted',
  EXCEPTION_REVOKED:          'Exception Revoked',
  EXCEPTION_LAPSED:           'Exception Ran Out (Valid Until Passed)',
  PREREG_CREATED:             'Preregistration Created',
  PREREG_CANCELLED:           'Preregistration Cancelled',
  PREREG_CAPTURED:            'Preregistration Captured (Session Opened)',
  PREREG_HELD_INELIGIBLE:     'Preregistration Held (Student May No Longer Sit the Series)',
  PREREG_REFUNDED_AT_DEADLINE: 'Preregistration Refunded (Series Never Opened)',
  REMARK_REQUESTED:           'Remark Requested',
  REMARK_APPROVED:            'Remark Approved by Parent',
  REMARK_REJECTED:            'Remark Rejected by Parent',
  REMARK_CONSENT_CONFIRMED:   'Remark Consent Confirmed',
  REMARK_SUBMITTED_TO_BOARD:  'Remark Submitted to Board',
  REMARK_OUTCOME_RECORDED:    'Remark Outcome Recorded',
  REMARK_CANCELLED:           'Remark Cancelled',
  RESULTS_RECORDED:           'Exam Results Recorded',
  STAFF_USER_CREATED:         'User Account Created by Staff',
  DESK_FAMILY_ONBOARDED:      'Family Onboarded at Desk',
  DESK_REGISTRATION:          'Registration Processed at Desk',
  DESK_SCHOOL_FEE_COLLECTED:  'School Fee Collected at Desk',
  PAYMENT_REVERSED:           'Payment Confirmation Reversed',
  CHANGE_REQUEST_CREATED:     'Drop/Swap Request Created',
  CHANGE_REQUEST_APPROVED:    'Drop/Swap Request Approved',
  CHANGE_REQUEST_REJECTED:    'Drop/Swap Request Rejected',
  CHANGE_REQUEST_CANCELLED:   'Drop/Swap Request Cancelled',
  DIRECT_DROP_EXECUTED:       'Direct Drop by Parent',
  DIRECT_SWAP_EXECUTED:       'Direct Swap by Parent',
  ESCROW_TRANSFER:            'Escrow Transfer',
  WITHDRAWAL_REQUESTED:       'Withdrawal Request Created',
  WITHDRAWAL_FULFILLED:       'Withdrawal Fulfilled',
  WITHDRAWAL_REJECTED:        'Withdrawal Rejected',
  USER_UPDATED:               'User Profile Updated',
  USER_UPDATED_BY_ADMIN:      'User Updated by Admin',
  USER_GRADE_CHANGED:         'Student Grade Changed',
  LINK_REQUESTED:             'Link Requested by Parent',
  LINK_APPROVED:              'Link Approved by Student',
  LINK_REJECTED:              'Link Rejected by Student',
  LINK_REMOVED:               'Link Removed by Admin',
  REMARK_FEE_SET:             'Remark Fee Set',
  REMARK_DEADLINE_SET:        'Remark Deadline Set',
  REMARK_PAYMENT_INITIATED:   'Remark Payment Initiated',
  REMARK_PAYMENT_CONFIRMED:   'Remark Fee Confirmed — Awaiting Submission',
  ADMIN_ANNOUNCEMENT:         'Admin Announcement Sent',
  STUDENT_COHORT_CORRECTED:   'Student Cohort Corrected',
  STUDENT_COHORT_INFERRED:    'Student Cohort Inferred (Backfill)',
  STUDENT_COHORT_RECORDED:    'Student Grade Recorded at First Setup',
  STUDENT_COHORT_UNRECORDED:  'Student Grade Not Recorded (Backfill)',
  STUDENT_LEFT:               'Student Left the School',
  STUDENT_READMITTED:         'Student Readmitted',
  TEACHER_ACCOUNT_LINKED:     'Teacher Record Linked to Account',
  SESSION_SERIES_CORRECTED:   'Session Exam Series Corrected',
  SETTING_CHANGED:            'School Setting Changed',
  FILE_UPLOADED:              'File Uploaded',
  ACADEMIC_YEAR_CREATED:      'Academic Year Created',
  ACADEMIC_YEAR_UPDATED:      'Academic Year Updated',
  TERM_CREATED:               'Term Created',
  TERM_UPDATED:               'Term Updated',
  TERM_DELETED:               'Term Deleted',
  CALENDAR_ENTRY_CREATED:     'Calendar Day Added',
  CALENDAR_ENTRY_DELETED:     'Calendar Day Removed',
  BELL_SCHEDULE_CREATED:      'Bell Schedule Created',
  BELL_SCHEDULE_UPDATED:      'Bell Schedule Updated',
  BELL_PERIODS_REPLACED:      'Bell Periods Saved',
  BELL_SCHEDULE_DELETED:      'Bell Schedule Deleted',
  ROOM_CREATED:               'Room Created',
  ROOM_UPDATED:               'Room Updated',
  SECTION_CREATED:            'Section Created',
  SECTION_UPDATED:            'Section Updated',
  SECTION_DELETED:            'Section Deleted',
  SECTION_MEMBERS_ADDED:      'Students Added to Section',
  SECTION_MEMBERSHIP_ENDED:   'Student Left Section',
  SECTIONS_ROLLED_OVER:       'Sections Rolled Over to New Year',
  BOARD_UPDATED:              'Exam Board Updated',
  QUALIFICATION_CREATED:      'Qualification Added',
  QUALIFICATION_UPDATED:      'Qualification Updated',
  QUALIFICATION_UNITS_SET:    'Units Counting Toward an Award Set',
  QUALIFICATION_OPTION_CREATED: 'Option Code Added',
  QUALIFICATION_OPTION_UPDATED: 'Option Code Updated',
  EXAM_UNIT_CREATED:          'Unit Added',
  EXAM_UNIT_UPDATED:          'Unit Updated',
  SUBJECT_CATALOGUE_MAPPED:   'Subject Mapped to the Catalogue',
  CATALOGUE_STARTER_LOADED:   'Catalogue Starter Set Loaded',
  BOARD_SERIES_CREATED:       'Board Series Added',
  BOARD_SERIES_UPDATED:       'Board Series Dates Updated',
  BOARD_SERIES_DELETED:       'Board Series Removed',
  BOARD_SERIES_DEADLINE_SET:  'Board Entry Deadline Set',
  SESSION_BOARD_SERIES_SET:   'Window Board Series Set',
  REGISTRATION_SERIES_MOVED:  'Registration Moved to Another Series',
  SUBJECT_ROUTE_MOVED:        "A Window's Route for a Subject Moved to Its New Board",
  SUBJECT_BOARD_CHANGED:      "Subject's Board Changed",
  SUBJECT_BOARD_INFERRED:     'Subject Board Inferred (Backfill)',
  REGISTRATION_SERIES_INFERRED: 'Registration Series Inferred (Backfill)',
  REGISTRATION_SERIES_INFERENCE_CHECKED: 'Inferred Series Checked by Staff',
  SUBJECT_NOT_OFFERED_INFERRED: 'Subject Not Offered in a Window (Backfill)',
  SUBJECT_BOARD_INFERENCE_CHECKED: "Subject's Inferred Board Checked by Staff",
  ENROLMENT_CREATED:          'Course Enrolment Added',
  ENROLMENT_UPDATED:          'Course Enrolment Changed',
  ENROLMENT_ENDED:            'Course Enrolment Ended',
  ENROLMENTS_BULK_CREATED:    'Course Enrolments Created in Bulk',
  REWORK_BACKFILL_SESSION:    'Window Converted to a Session (Migration)',
  REWORK_BACKFILL_OFFER:      'Subject Converted to an Offer (Migration)',
  REWORK_BACKFILL_FEE:        'Board Fee Converted (Migration)',
  REWORK_BACKFILL_LINE:       'Registration Converted to a Line (Migration)',
  SESSION_COPIED:             'Session Copied From Another',
  SESSION_OFFER_CREATED:      'Subject Added to a Session',
  SESSION_OFFER_UPDATED:      'Session Subject Updated',
  SESSION_OFFER_DELETED:      'Subject Removed From a Session',
  SESSION_OFFER_TEACHER_REPLACED: 'Teacher Replaced on a Session Subject',
  OFFER_ITEM_CREATED:         'Item Added to a Subject',
  OFFER_ITEM_UPDATED:         'Item Updated',
  OFFER_ITEM_DELETED:         'Item Removed',
  OFFER_ITEM_SERIES_CHANGED:  'Item Moved to Another Board Series',
  LINE_SERIES_MOVED:          'Line Moved With Its Item',
  LINE_TEACHER_REPLACED:      'Line Teacher Replaced',
  BOARD_FEES_SET:             'Board Fees Set',
  BOARD_FEES_COPIED:          'Board Fees Copied (Provisional)',
  BOARD_FEES_CONFIRMED:       'Board Fees Confirmed',
  BOARD_FEES_REPRICED:        'Unpaid Lines Re-priced',
  LINE_REPRICED:              'Line Re-priced (Board Fee Confirmed)',
  LINE_PRICE_KEPT: 'Line price kept (fee confirmed)',
  LINE_DUE_MOVED:             'Line Due Date Moved',
  GRADE10_BULK_COMMITTED:     'Grade 10 Registered in Bulk',
  CHARGE_CREATED: 'Charge Added',
  CHARGE_REQUESTED: 'Charge Requested by the Family',
  CHARGE_ACCEPTED: 'Charge Request Accepted',
  CHARGE_CANCELLED: 'Charge Cancelled',
  CHARGE_REPRICED: 'Charge Price Changed by an Exception',
  CHARGE_PAID: 'Charge Paid',
  CHARGE_REOPENED: 'Charge Reopened (Payment Reversed)',
  CHARGE_SETTLED: 'Pushed School Fee Settled',
  CHARGE_REFUNDED: 'Charge Refunded to Escrow',
  CHARGE_CLOSED_AT_DEADLINE: 'Charge Closed at the Service Deadline',
  CHARGE_PAYMENT_INITIATED: 'Charge Payment Started',
  SCHOOL_FEE_PUSHED: 'School Fee Pushed to Families',
  PLAN_CAPTURED: 'Instalment Plan Captured into the Line',
  PLAN_SETTLED: 'Instalment Plan Settled',
  EXCEPTION_CONFIRMED: 'Migrated Exception Confirmed',
  EXCEPTION_USED: 'One-Shot Exception Used',
  BOARD_SERVICE_UPDATED: 'Board Service Updated',
  SERVICE_DEADLINES_SET: 'Board Service Deadlines Set',
  SERVICE_FEES_SET: 'Board Service Fees Set',
  SERVICE_FEE_DEFAULT_COPIED: 'Board Service Fee Copied from the Defaults',
  DESK_DROP_EXECUTED: 'Dropped at the Desk after the Deadline',
  REWORK_BACKFILL_EXCEPTION: 'Exception Moved onto the Policy Registry',
  REWORK_BACKFILL_SERVICE: 'Remark Fees and Deadlines Moved onto Board Services',
  PRIOR_SITTING_VERIFIED:     'Declared Sitting Verified',
  PRIOR_SITTING_REJECTED:     'Declared Sitting Rejected',
  LINE_DROPPED_UNVERIFIED:    'Line Dropped: Sitting Unverified at the Deadline',
  LINE_TEACHER_CHANGED:       'Line Teacher Changed',
  TEACHING_GROUPS_FORMED:     'Teaching Groups Formed from Enrolment',
  TEACHING_GROUP_CREATED:     'Teaching Group Added',
  TEACHING_GROUP_UPDATED:     'Teaching Group Changed',
  TEACHING_GROUP_MEMBERS_ADDED: 'Students Added to a Teaching Group',
  TEACHING_GROUP_MEMBERS_ENDED: 'Students Taken out of a Teaching Group',
  TEACHING_GROUP_SPLIT:       'Teaching Group Split',
  TEACHING_GROUPS_MERGED:     'Teaching Groups Merged',
  TEACHING_GROUP_ARCHIVED:    'Teaching Group Retired',
  SCHEDULE_RULES_SET:         'Timetable Rules Set',
  TIMETABLE_CREATED:          'Timetable Draft Created',
  TIMETABLE_UPDATED:          'Timetable Renamed',
  TIMETABLE_DELETED:          'Timetable Draft Deleted',
  TIMETABLE_LESSON_MOVED:     'Lesson Moved',
  TIMETABLE_LESSON_LOCKED:    'Lesson Locked or Unlocked',
  TIMETABLE_GENERATED:        'Timetable Generated',
  TIMETABLE_PUBLISHED:        'Timetable Published',
  TEACHER_ABSENCE_RECORDED:   'Teacher Absence Recorded',
  TEACHER_ABSENCE_CANCELLED:  'Teacher Absence Cancelled',
  COVER_ASSIGNED:             'Cover Assigned',
  LESSON_CANCELLED:           'Lesson Cancelled',
  COVER_REMOVED:              'Cover Removed',
  CALENDAR_FEED_CREATED:      'Calendar Feed Link Made',
  CALENDAR_FEED_REVOKED:      'Calendar Feed Link Revoked',
};

// ─── Query Filters ────────────────────────────────────────────────────────────

/**
 * Query parameters for the admin audit log viewer (REP-006).
 * All filters are optional — returns all entries when empty.
 */
export const AuditLogsQuery = z.object({
  userId:     z.string().min(1, 'Invalid user ID').optional(),
  action:     AuditActionSchema.optional(),
  entityType: AuditEntityTypeSchema.optional(),
  entityId:   z.string().optional(),
  dateFrom:   z.string().optional(),
  dateTo:     z.string().optional(),
  format:     z.enum(['json', 'csv']).optional(),
  limit: z
    .string()
    .optional()
    .transform((v) => (v ? Math.min(parseInt(v, 10) || 50, 200) : 50)),
  offset: z
    .string()
    .optional()
    .transform((v) => (v ? parseInt(v, 10) || 0 : 0)),
});
export type AuditLogsQueryType = z.infer<typeof AuditLogsQuery>;
